---
title: Product Management
title-link: https://thenounproject.com/kerismaker/collection/product-management-line/?i=3656728
content: icon
used-in: Home
artist: Tezar Tantular
provider: Noun Project 
provider-link: https://thenounproject.com/
image-url: /assets/images/communities-of-practice/homepage-icons/product-management.png
alt: 'Product Management Icon'
type: icon
---